package eu.nimble.service.catalog.search.impl.dao.enums;

public enum PropertySource {

<<<<<<< HEAD
	CUSTOM_DECIMAL, CUSTOM_STRING, DIRECT_PROPERTIES,ADDITIONAL_ITEM_PROPERTY, DOMAIN_SPECIFIC_PROPERTY, DIMENSION, DESCRIPTION, CERTIFICATE, NAME, MANUFACTURER_PARTY, MANUFACTURER_ITEMS_IDENTIFICATION, UNKNOWN, CATALOGUE_DOCUMENT_REFERENCE
=======
	CUSTOM_DECIMAL, CUSTOM_STRING, DIRECT_PROPERTIES,ADDITIONAL_ITEM_PROPERTY, DOMAIN_SPECIFIC_PROPERTY, DIMENSION, DESCRIPTION, CERTIFICATE, NAME, MANUFACTURER_PARTY, MANUFACTURER_ITEMS_IDENTIFICATION
>>>>>>> 435465c206650462162b92beebb5ee64acd49df6
}
