package eu.nimble.service.catalog.search.impl.dao.enums;

public enum PropertySource {

	ADDITIONAL_ITEM_PROPERTY, DOMAIN_SPECIFIC_PROPERTY, DIMENSION, DESCRIPTION, CERTIFICATE, NAME, MANUFACTURER_PARTY, MANUFACTURER_ITEMS_IDENTIFICATION
}
