//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 09:46:29 PM MEZ 
//


package eu.nimble.service.catalog.search.mediator.datatypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Service" type="{}Service" maxOccurs="unbounded"/>
 *         &lt;element name="URLOfTripleStore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InformationRequestServiceConfigurationFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "service",
    "urlOfTripleStore",
    "informationRequestServiceConfigurationFile"
})
@XmlRootElement(name = "InformationServices")
public class InformationServices {

    @XmlElement(name = "Service", required = true)
    protected List<Service> service;
    @XmlElement(name = "URLOfTripleStore", required = true)
    protected String urlOfTripleStore;
    @XmlElement(name = "InformationRequestServiceConfigurationFile", required = true)
    protected String informationRequestServiceConfigurationFile;

    /**
     * Gets the value of the service property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the service property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Service }
     * 
     * 
     */
    public List<Service> getService() {
        if (service == null) {
            service = new ArrayList<Service>();
        }
        return this.service;
    }

    /**
     * Gets the value of the urlOfTripleStore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURLOfTripleStore() {
        return urlOfTripleStore;
    }

    /**
     * Sets the value of the urlOfTripleStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURLOfTripleStore(String value) {
        this.urlOfTripleStore = value;
    }

    /**
     * Gets the value of the informationRequestServiceConfigurationFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformationRequestServiceConfigurationFile() {
        return informationRequestServiceConfigurationFile;
    }

    /**
     * Sets the value of the informationRequestServiceConfigurationFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformationRequestServiceConfigurationFile(String value) {
        this.informationRequestServiceConfigurationFile = value;
    }

}
