//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 09:46:29 PM MEZ 
//


package eu.nimble.service.catalog.search.mediator.datatypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OutputWrapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OutputWrapper">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="javaClassForStorage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="configurationForStorage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutputWrapper", propOrder = {
    "javaClassForStorage",
    "configurationForStorage"
})
public class OutputWrapper {

    @XmlElement(required = true)
    protected String javaClassForStorage;
    protected String configurationForStorage;

    /**
     * Gets the value of the javaClassForStorage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaClassForStorage() {
        return javaClassForStorage;
    }

    /**
     * Sets the value of the javaClassForStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaClassForStorage(String value) {
        this.javaClassForStorage = value;
    }

    /**
     * Gets the value of the configurationForStorage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigurationForStorage() {
        return configurationForStorage;
    }

    /**
     * Sets the value of the configurationForStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigurationForStorage(String value) {
        this.configurationForStorage = value;
    }

}
